### ISSUE TITLE
Please add the ability to choose a half rating

### ISSUE THREAD

**Issue by web-crab** [smastrom/react-rating#14]
The component is amazing! But it’s a pity that such an opportunity is missing, it is very necessary

**Comment by smastrom** [comment]
Hi @web-crab, thank you for reaching out and for your interest.

Unfortunately, the ability to set "half-ratings" was one of the first things that I deliberately decided to not include in this package when I started brainstorming about it last year.

The reason is very simple: I think they are just a way to visually describe a rating more accurately, but definitely not something that facilitates its submission.

In fact, I can't recall a single, reputable e-commerce or service that ever prompted me to select a "half-rating".

If you really need this feature, you should consider using a different package. If I may suggest one, [Mantine Rating](
https://mantine.dev/core/rating/) would be a great fit for your use case.
