### ISSUE TITLE
MouseEvent Not Returning on onChange in Rating Component, Causing Unintended Navigation

### ISSUE THREAD

**Issue by abdulvahidkpOctalogic** [smastrom/react-rating#16]
I'm currently facing an issue with the rating component, specifically when used within cards containing navigation links. Upon attempting to change the rating, it triggers navigation to the card's link unintentionally.

This behavior poses a usability problem, especially when the rating component is embedded within cards that are meant to serve as navigation links. The expected functionality is to change the rating without triggering navigation.

**Comment by mike667** [comment]
Hello @smastrom. Unfortunately, this fix broke our functionality. Could this be as a custom option? Like ebaleClickPreventDefault.

Thank you.

**Comment by smastrom** [comment]
> Hello @smastrom. Unfortunately, this fix broke our functionality. Could this be as a custom option? Like enableClickPreventDefault.
> 
> Thank you.

Which kind of functionality did it break?

**Comment by mike667** [comment]
We use rating selects inside links. And we catch click events in react parent components. With this changes we need to rethink our flow, because it's not possible to configure previous behavior or set our custom click handler.

**Comment by mike667** [comment]
Hello @smastrom, Is it possible to do something with it? Or I can do merge request.

But I'm not sure which approach use. I think click handler should not be blocked. If something is inside link, it should behave as a link.

**Comment by smastrom** [comment]
Hi @mike667, I left the issue opened hoping for somebody to came up with your same issue but we had no success.

I hear you and it's fair to let consumers decide if `preventDefault` (and `stopPropagation`) should be called.

Since this can be implemented with few lines of code without braking the API and the current behavior, I can work at that.

The best way that comes to my mind is to create two new props named `preventDefault` and `stopPropagation`. Each prop can receive one of these values: `all` | `keydown` | `click` | `all`, both having `all` set by default.

I'll work at it soon.
