### ISSUE TITLE
Rating Star not shown at Popup

### ISSUE THREAD

**Issue by sathiyapriyaG** [smastrom/react-rating#17]
When I try this package on my Website, It works on Normal pages. But not at the Modal Popup. The CSS is rendered correctly. But it is not shown. Also, the half-star rating is not working while selecting the stars. Please check the attachment.

<img width="1346" alt="image" src="https://github.com/smastrom/react-rating/assets/32445438/20290df2-a979-48fe-bc38-a265f8fc42e4">

Could someone please assist me with this?

This is my code.

```
import { Rating as ReactRating, RoundedStar } from '@smastrom/react-rating';
import '@smastrom/react-rating/style.css';
<ReactRating  
      value={1.5} 
      readOnly 
      style={{ maxWidth: 130 }}       
      itemStyles={{
      itemShapes: RoundedStar,
      activeFillColor: '#EB0444',
      inactiveFillColor: '#E2E2E2',
    }}
/>
```

**Comment by smastrom** [comment]
Hi @sathiyapriyaG, half-star rating is only supported in `readOnly` mode. This is by design. You can read more about it [here](https://github.com/smastrom/react-rating/issues/14).

Regarding the SVGs (stars) not rendering correctly there's a workaround that you can implement until a fix is released. [Original issue](https://github.com/smastrom/react-rating/issues/10).

The bug is that currently, `Rating` is not able to calculate the stars size when it is mounted inside a component with `display: none`. I am sure that when your modal is closed, you still have it in the DOM, but with `display: none` applied.

To workaround this, you should manually mount `Rating` when the parent doesn't have anymore `display: none`.

Inside the component that renders `<Rating />` in the modal, initalize a boolean state with `false` that servers this purpose (`isModalReady`):

```js
import { useState } from 'react'
import { Rating as ReactRating } from '@smastrom/react-rating'

export function Rating({ isModalOpen }) {
   const [isModalReady, setIsModalReady] = useState(false)

   if (!isModalReady) return null

   return (
      <ReactRating
         value={1.5}
         readOnly
         style={{ maxWidth: 130 }}
      />
   )
}
```

Then in the parent component that handles the state that toggles the modal, pass that state to the component that renders rating:

```js
import { useState } from 'react'
import { Rating } from './Rating'

export function Modal() {
   const [isModalOpen, setIsModalOpen] = useState(false)

   return (
      <>
         <button onClick={() => setIsModalOpen((prev) => !prev)}>Open Modal</button>
         <div style={{ display: isModalOpen ? 'block' : 'none' }}>
            <h1>My Modal</h1>
            <Rating isModalOpen={isModalOpen} />
         </div>
      </>
   )
}
```

Finally add this check in the component that renders `Rating`:

```js
import { useLayoutEffect, useState } from 'react'
import { Rating as ReactRating } from '@smastrom/react-rating'

export function Rating({ isModalOpen }) {
   const [isModalReady, setIsModalReady] = useState(false)

   useLayoutEffect(() => {
      if (isModalOpen) {
         setIsModalReady(true)
      } else {
         setIsModalReady(false)
      }
   }, [isModalOpen])

   if (!isModalReady) return null

   return (
      <ReactRating
         value={1.5}
         readOnly
         style={{ maxWidth: 130 }}
      />
   )
}
```

You can find a working example on [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-6tm7d5?file=src%2FModal.tsx).

**Comment by smastrom** [comment]
Follow in #10
